version: '2'
services:

  rasa:
    build: ./rasa/.
    container_name: mandrake-rasa
    ports:
      - "5000:5000"
    volumes:
      - ./rasa/config/config.json:/app/config_mitie.json:rw
      - ./rasa/config/train.json:/app/data/examples/rasa/demo-rasa.json
      - ./rasa/models:/app/models
    environment:
      - SERVICE_NAME=mandrake-rasa
    networks:
      - mandrakenet
    depends_on:
      - consul
      - registrator
    command: python -m rasa_nlu.server -c config_mitie.json --server_model_dirs="${RASA_MODEL}"

  node-red:
    user: root
    build: .
    ports:
      - "9000:9000"
    container_name: mandrake-node-red
    environment:
      - SERVICE_NAME=mandrake-node-red
    volumes:
       - "./data:/home/mandrake-ai/data"
    depends_on:
      - rasa
      - mosquitto
      - consul
      - registrator
    environment:
      - SERVICE_NAME=node-red
    networks:
      - mandrakenet
    command: ["npm", "start"]

  mosquitto:
    image: "eclipse-mosquitto:1.4.8"
    container_name: mosquitto-server
    environment:
      - SERVICE_NAME=mosquitto
    networks:
      - mandrakenet
    ports:
      - "1883:1883"
      - "9001:9001"
      - "9883:9883"
    depends_on:
      - consul
      - registrator

  registrator:
    image: gliderlabs/registrator:latest
    command: "-internal consul://consul:8500"
    container_name: registrator
    hostname: registrator
    networks:
      - mandrakenet
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  consul:
    image:  gliderlabs/consul-server:latest
    command: "-bootstrap -client 0.0.0.0"
    environment:
      - SERVICE_NAME=consul
    container_name: consul
    hostname: consul
    networks:
      - mandrakenet
    ports:
      - 8500:8500

networks:
  mandrakenet:
    driver: bridge
