version: '2'
services:

  mandrake-db:
    user: root
    image: mongo:latest
    restart: always
    hostname: mandrake-db
    command: ["mongod", "--smallfiles"]
    container_name: mandrake-db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db:rw

  mandrake-nlp:
    user: root
    image: yantrashala/mandrake-nlp
    restart: always
    hostname: mandrake-nlp
    container_name: mandrake-nlp
    ports:
      - "5000:5000"
    volumes:
      - ./config/config-mandrake-ai.json:/app/config.json:rw
      - ./config/mandrake-ai.json:/app/data/mandrake/mandrake-ai.json:ro
      - ./data/models:/app/models
    environment:
      - SERVICE_NAME=mandrake-nlp
    command: python -m rasa_nlu.server -c config.json

  mandrake-flow:
    user: root
    image: yantrashala/mandrake-flow
    restart: always
    hostname: mandrake-flow
    ports:
      - "9000:9000"
    container_name: mandrake-flow
    environment:
      - SERVICE_NAME=mandrake-flow
    volumes:
       - "./data:/home/mandrake-ai/data"
    depends_on:
      - mandrake-nlp
      - mandrake-mq
    links:
      - mandrake-nlp
      - mandrake-mq
    environment:
      - SERVICE_NAME=mandrake-flow
    command: ["npm", "start"]

  mandrake-connector:
    user: root
    image: yantrashala/mandrake-connector
    restart: always
    container_name: mandrake-connector
    hostname: mandrake-connector
    depends_on:
      - mandrake-db
    links:
      - mandrake-db
    environment:
      - SERVICE_NAME=mandrake-connector
      - NODE_ENV=developemnt
    ports:
      - "6060:6060"
    command: ["yarn", "start"]

  mandrake-mq:
    user: root
    restart: always
    image: "eclipse-mosquitto:1.4.8"
    container_name: mandrake-mq
    hostname: mandrake-mq
    environment:
      - SERVICE_NAME=mandrake-mq
    ports:
      - "1883:1883"
      - "9001:9001"
      - "9883:9883"
