version: '2'
services:

  mandrake-flow:
    user: root
    build: ./flow/.
    restart: always
    ports:
      - "9000:9000"
    container_name: mandrake-flow
    environment:
      - SERVICE_NAME=mandrake-flow
    volumes:
       - "./data:/home/mandrake-ai/data"
    depends_on:
      - mandrake-nlp
      - mandrake-mq
    links:
      - mandrake-nlp
      - mandrake-mq
    environment:
      - SERVICE_NAME=mandrake-flow
    command: ["npm", "start"]

  mandrake-mq:
    user: root
    restart: always
    image: "eclipse-mosquitto:1.4.8"
    container_name: mandrake-mq
    environment:
      - SERVICE_NAME=mandrake-mq
    ports:
      - "1883:1883"
      - "9001:9001"
      - "9883:9883"
